# Generated by Django 6.0.4 on 2026-04-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_id', models.IntegerField(unique=True, verbose_name='ID пользователя')),
                ('quantity', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('buy_datetime', models.DateTimeField(auto_now_add=True)),
                ('is_refunded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PriceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.FloatField()),
                ('new_price', models.FloatField()),
                ('discount', models.BooleanField(default=False)),
                ('date_change', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProxyReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.IntegerField(unique=True, verbose_name='ID страны')),
                ('name', models.TextField(verbose_name='Название страны')),
                ('proxy_type_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_username', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='ID пользователя')),
                ('top_up_amount', models.FloatField(default=0.0)),
                ('consume_records', models.FloatField(default=0.0)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('can_receive_messages', models.BooleanField(default=False)),
            ],
        ),
    ]
