# Generated by Django 6.0.4 on 2026-04-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonsMedia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('media_id', models.CharField()),
                ('button', models.TextField(unique=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'buttons_media',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Buyproxy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'buyProxy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('proxy_type_id', models.IntegerField()),
                ('country_id', models.IntegerField()),
                ('period_days', models.CharField()),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'cart_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'carts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(unique=True)),
                ('country_flag', models.CharField(unique=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('processing_payment_id', models.IntegerField()),
                ('message_id', models.IntegerField()),
                ('is_paid', models.BooleanField()),
                ('expire_datetime', models.DateTimeField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periods',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period_days', models.CharField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'periods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proxies',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'proxies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProxyTypes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('proxy_type', models.CharField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'proxy_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('telegram_username', models.CharField(unique=True)),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('top_up_amount', models.FloatField()),
                ('consume_records', models.FloatField()),
                ('registered_at', models.DateTimeField()),
                ('can_receive_messages', models.BooleanField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='PriceChange',
        ),
        migrations.DeleteModel(
            name='ProxyReplacement',
        ),
        migrations.DeleteModel(
            name='TelegramUser',
        ),
        migrations.AlterModelOptions(
            name='buys',
            options={'managed': False},
        ),
    ]
