# Generated by Django 6.0.4 on 2026-04-17 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0002_buttonsmedia_buyproxy_cartitems_carts_countries_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='buys',
            table='buys',
        ),
    ]
